### ISSUE TITLE
support

### ISSUE THREAD

**Issue by HadeerElbahnasawy1991** [farmassistX/farmassist#19]
it doesn't work

**Comment by menoc61** [comment]
Hey 👋🏾

**Comment by HadeerElbahnasawy1991** [comment]
hi send me your whats app number, please

**Comment by HadeerElbahnasawy1991** [comment]
I hope this email finds you well. My name is [hadeer], and I came across
your project [farmassist] on GitHub. I was truly impressed by the work
you've done, and I believe it has great potential for

I am very interested in taking this project to the next level by
implementing it in a practical environment. I would love to collaborate
with you and discuss how we can work together to bring this project

If you are open to this idea, I would be more than happy to provide
additional details about my vision for the project and how we could
proceed. I am confident that, with your expertise and my enthusiasm,

Best regards,

hadeer

**Comment by scottykilgore** [comment]
I'm putting everyone in jail that stole my online businesses and been collecting my money off my businesses vet that. Now I want an investigation into who has been in my GitHub account at once or I'll sue!!!!

**Comment by HadeerElbahnasawy1991** [comment]
Dear Scotty Kilgore,

I apologize if there has been any misunderstanding regarding my previous
communication. I reached out to you to discuss potential collaboration on a
smart farming project. I want to assure you that I have no intention of
using any code or material that does not belong to me. Integrity is very
important to me, and I do not engage in the practice of using, modifying,
or selling others' work without proper permissions.

I understand your concerns about protecting your work, and I completely
respect that. My intention has always been to collaborate transparently and
professionally. Please rest assured that I am not like those who take
others' code and manipulate it for personal gain, as that is not aligned
with my values.

I hope we can clear up any confusion and have a constructive conversation
about potential collaboration moving forward.

Thank you for your understanding.

Best regards,
Hadeer

**Comment by scottykilgore** [comment]
My phone number is 4234570016 I suggest that you contact the FBI about this
matter you may also want to call me you have a stolen online business and I
want everything back that has been taken from me and what's been made off
my business
